apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: streamlit-app
  template:
    metadata:
      labels:
        app: streamlit-app
    spec:
      containers:
      - name: streamlit-app
        image: gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.IMAGE_NAME }}:latest
        ports:
        - containerPort: 8501